## 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np

# Display all floating-point numbers without scientific notation
pd.set_option('display.float_format', lambda x: f'{x:,.6f}')
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("../data/raw/World-Stock-Prices-Dataset.csv")

df.head()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
0,2025-07-03 00:00:00-04:00,6.630000,6.740000,6.615000,6.640000,"4,209,664.000000",peloton,PTON,fitness,usa,0.000000,0.000000,NaN
1,2025-07-03 00:00:00-04:00,106.750000,108.370003,106.330101,107.339996,"560,190.000000",crocs,CROX,footwear,usa,0.000000,0.000000,NaN
2,2025-07-03 00:00:00-04:00,122.629997,123.050003,121.550003,121.930000,"36,600.000000",adidas,ADDYY,apparel,germany,0.000000,0.000000,NaN
3,2025-07-03 00:00:00-04:00,221.705002,224.009995,221.360001,223.410004,"29,295,154.000000",amazon,AMZN,e-commerce,usa,0.000000,0.000000,NaN
4,2025-07-03 00:00:00-04:00,212.145004,214.649994,211.810104,213.550003,"34,697,317.000000",apple,AAPL,technology,usa,0.000000,0.000000,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
310117,2000-01-03 00:00:00-05:00,38.147537,38.255972,35.935457,37.496925,"53,076,000.000000",cisco,CSCO,technology,usa,0.000000,0.000000,NaN
310118,2000-01-03 00:00:00-05:00,25.215814,25.330655,24.690826,24.772856,"2,173,400.000000",3m,MMM,manufacturing,usa,0.000000,0.000000,NaN
310119,2000-01-03 00:00:00-05:00,72.313085,72.405794,71.756831,72.034958,"21,200.000000",toyota,TM,automotive,japan,0.000000,0.000000,NaN
310120,2000-01-03 00:00:00-05:00,7.289986,7.342182,7.098602,7.168196,"882,200.000000",nordstrom,JWN,retail,usa,0.000000,0.000000,NaN
310121,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,"5,825,700.000000",american eagle outfitters,AEO,apparel,usa,0.000000,0.000000,NaN

- Looking at the data we have data from january 3rd to july 3rd 2025.
- The data has 13 features.
- Open	High	Low	Close are the main variables in the data.

In [4]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 310122
Columns: 13

## 2. Dataset Overview

In [5]:
# 1. Shape
rows, cols = df.shape

print(f"Number of observations: {rows:,}")
print(f"Number of variables: {cols}")

Number of observations: 310,122
Number of variables: 13

In [6]:
# 2. Dataset Size
size_mb = df.memory_usage(deep=True).sum() / (1024**2)

print(f"Dataset Size: {size_mb:.2f} MB")

Dataset Size: 106.60 MB

In [7]:
# 3. Column Names
pd.DataFrame({
    "Variable": df.columns
})

         Variable
0            Date
1            Open
2            High
3             Low
4           Close
5          Volume
6      Brand_Name
7          Ticker
8    Industry_Tag
9         Country
10      Dividends
11   Stock Splits
12  Capital Gains

In [8]:
# 4. Data Types Assessment
dtype_summary = pd.DataFrame({
    "Variable": df.columns,
    "Data Type": df.dtypes.values
})

dtype_summary

         Variable Data Type
0            Date       str
1            Open   float64
2            High   float64
3             Low   float64
4           Close   float64
5          Volume   float64
6      Brand_Name       str
7          Ticker       str
8    Industry_Tag       str
9         Country       str
10      Dividends   float64
11   Stock Splits   float64
12  Capital Gains   float64

In [9]:
# datatypes counts 
df.dtypes.value_counts()

float64    8
str        5
Name: count, dtype: int64

In [10]:
# 5. Missing Values Assessment
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": round(df.isnull().mean()*100,2)
})

missing.sort_values(
    by="Missing Percentage",
    ascending=False
)

               Missing Count  Missing Percentage
Capital Gains         310120          100.000000
Open                       0            0.000000
High                       0            0.000000
Low                        0            0.000000
Date                       0            0.000000
Close                      0            0.000000
Volume                     0            0.000000
Ticker                     0            0.000000
Brand_Name                 0            0.000000
Industry_Tag               0            0.000000
Country                    0            0.000000
Dividends                  0            0.000000
Stock Splits               0            0.000000

In [11]:
# 6. Total Missing
total_missing = df.isnull().sum().sum()

print(f"Total Missing Values: {total_missing}")

Total Missing Values: 310120

In [12]:
# 7. Duplicate Records
duplicates = df.duplicated().sum()

print(f"Duplicate Records: {duplicates}")

Duplicate Records: 0

In [13]:
# 8. Cardinality Assessment

categorical_cols = df.select_dtypes(
    include=["object"]
).columns

cardinality = pd.DataFrame({
    "Variable": categorical_cols,
    "Unique Values":
    [df[col].nunique() for col in categorical_cols]
})

cardinality.sort_values(
    by="Unique Values",
    ascending=False
)

C:\Users\admin\AppData\Local\Temp\ipykernel_19788\4179273457.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

       Variable  Unique Values
0          Date           6408
1    Brand_Name             62
2        Ticker             62
3  Industry_Tag             23
4       Country              7

In [14]:
# 9. Unique Value Exploration
for col in categorical_cols:
    
    print("="*50)
    print(col)
    print("="*50)
    
    print(df[col].value_counts().head(10))

==================================================
Date
==================================================
Date
2025-01-17 00:00:00-05:00    122
2025-01-10 00:00:00-05:00    122
2025-01-08 00:00:00-05:00    122
2024-12-31 00:00:00-05:00    122
2024-12-27 00:00:00-05:00    122
2024-12-24 00:00:00-05:00    122
2024-12-13 00:00:00-05:00    122
2024-12-06 00:00:00-05:00    122
2024-11-29 00:00:00-05:00    122
2024-11-27 00:00:00-05:00    122
Name: count, dtype: int64
==================================================
Brand_Name
==================================================
Brand_Name
marriott                     6471
amazon                       6470
apple                        6470
nike                         6470
target                       6470
the walt disney company      6470
costco                       6470
southwest airlines           6470
american eagle outfitters    6470
starbucks                    6470
Name: count, dtype: int64
==================================================
Ticker
==================================================
Ticker
MAR     6471
AMZN    6470
AAPL    6470
NKE     6470
TGT     6470
DIS     6470
COST    6470
LUV     6470
AEO     6470
SBUX    6470
Name: count, dtype: int64
==================================================
Industry_Tag
==================================================
Industry_Tag
technology         66957
retail             25842
automotive         24867
finance            22210
apparel            21069
food & beverage    19409
consumer goods     19407
entertainment      12342
gaming             11546
food               11415
Name: count, dtype: int64
==================================================
Country
==================================================
Country
usa            243606
japan           19403
germany         16225
netherlands     12938
france           8879
switzerland      6469
canada           2602
Name: count, dtype: int64

In [15]:
# 10. Numerical Summary Statistics
numerical_cols = df.select_dtypes(
    include=np.number
).columns

df[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Open,"310,122.000000",76.325431,141.684070,0.000000,15.932500,35.408120,83.996691,"3,445.580078"
High,"310,122.000000",77.198011,143.224109,0.000000,16.163165,35.809869,84.914656,"3,463.070068"
Low,"310,122.000000",75.434586,140.063617,0.000000,15.710323,34.982469,83.088609,"3,370.000000"
Close,"310,122.000000",76.338032,141.679129,0.198861,15.940000,35.407547,84.000000,"3,427.610107"
Volume,"310,122.000000","22,709,366.044795","85,657,437.802224",0.000000,"1,379,050.000000","4,591,641.500000","12,128,600.000000","7,421,640,800.000000"
Dividends,"310,122.000000",0.003643,0.069905,0.000000,0.000000,0.000000,0.000000,15.000000
Stock Splits,"310,122.000000",0.000875,0.115434,0.000000,0.000000,0.000000,0.000000,50.000000
Capital Gains,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [16]:
summary = pd.DataFrame({
    
    "Mean":
    df[numerical_cols].mean(),
    
    "Median":
    df[numerical_cols].median(),
    
    "Std":
    df[numerical_cols].std(),
    
    "Skewness":
    df[numerical_cols].skew(),
    
    "Kurtosis":
    df[numerical_cols].kurt()
    
})

summary

,Mean,Median,Std,Skewness,Kurtosis
Open,76.325431,35.408120,141.684070,8.233529,110.332036
High,77.198011,35.809869,143.224109,8.205535,109.461198
Low,75.434586,34.982469,140.063617,8.248666,110.701955
Close,76.338032,35.407547,141.679129,8.224337,109.989905
Volume,"22,709,366.044795","4,591,641.500000","85,657,437.802224",13.109585,367.720233
Dividends,0.003643,0.000000,0.069905,74.156743,"10,788.219352"
Stock Splits,0.000875,0.000000,0.115434,307.583068,"120,186.729157"
Capital Gains,0.000000,0.000000,0.000000,NaN,NaN

In [17]:
#11. Variable Classification Table
variable_summary = pd.DataFrame({
    
    "Variable": df.columns,
    
    "Type": [
        "Numerical"
        if df[col].dtype != "object"
        else "Categorical"
        for col in df.columns
    ]
    
})

variable_summary

         Variable       Type
0            Date  Numerical
1            Open  Numerical
2            High  Numerical
3             Low  Numerical
4           Close  Numerical
5          Volume  Numerical
6      Brand_Name  Numerical
7          Ticker  Numerical
8    Industry_Tag  Numerical
9         Country  Numerical
10      Dividends  Numerical
11   Stock Splits  Numerical
12  Capital Gains  Numerical

In [18]:
#12. Check for Leading/Trailing Spaces
# Check for extra spaces in categorical variables

categorical_cols = [
    "Brand_Name",
    "Ticker",
    "Industry_Tag",
    "Country"
]

for col in categorical_cols:
    df[col] = df[col].str.strip()

## Preliminary Data cleaning

In [19]:
# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"], utc=True)

# Define categorical variables
categorical_cols = [
    "Brand_Name",
    "Ticker",
    "Industry_Tag",
    "Country"
]

# Convert categorical variables
for col in categorical_cols:
    df[col] = df[col].astype("category")

# Define numerical variables
numerical_cols = [
    "Open",
    "High",
    "Low",
    "Close",
    "Volume",
    "Dividends",
    "Stock Splits",
    "Capital Gains"
]

# Ensure numerical variables are numeric
for col in numerical_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Verify data types
dtype_summary = pd.DataFrame({
    "Variable": df.columns,
    "Data Type": df.dtypes.astype(str)
})

dtype_summary

                    Variable            Data Type
Date                    Date  datetime64[us, UTC]
Open                    Open              float64
High                    High              float64
Low                      Low              float64
Close                  Close              float64
Volume                Volume              float64
Brand_Name        Brand_Name             category
Ticker                Ticker             category
Industry_Tag    Industry_Tag             category
Country              Country             category
Dividends          Dividends              float64
Stock Splits    Stock Splits              float64
Capital Gains  Capital Gains              float64

In [20]:
# Save first cleaned version of the dataset

df.to_csv(
    "../data/raw/df_clean_one.csv",
    index=False
)

print("df_clean_one.csv saved successfully.")

df_clean_one.csv saved successfully.